# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rooty
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080